### ISSUE TITLE
bbconf broken with pipestat updates

### ISSUE THREAD

**Issue by nsheff** [databio/bbconf#31]
pipestat updates have broken bbconf: 

```
 from bbconf import BedBaseConf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nsheff/.local/lib/python3.11/site-packages/bbconf/__init__.py", line 2, in <module>
    from bbconf.bbconf import *
  File "/home/nsheff/.local/lib/python3.11/site-packages/bbconf/bbconf.py", line 9, in <module>
    from pipestat.helpers import dynamic_filter
ImportError: cannot import name 'dynamic_filter' from 'pipestat.helpers' (/home/nsheff/.local/lib/python3.11/site-packages/pipestat/helpers.py)
```

**Comment by nsheff** [comment]
I think that fixed it.
