### ISSUE TITLE
error getting bedset info to elastic index

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bbconf#5]
I'm running across an error that might be coming from `bbconf` when I try to insert the `bedset` summary info into the `BEDSET_INDEX`. Looks like it has to do with the bed files md5sums:

Traceback (most recent call last):
  File "/home/jev4xy/Desktop/bedbuncher/project/../bedbuncher.py", line 263, in <module>
    sys.exit(main())
  File "/home/jev4xy/Desktop/bedbuncher/project/../bedbuncher.py", line 250, in main
    bbc.insert_bedsets_data(data=bedset_summary_info, doc_id=bedset_digest)
  File "/home/jev4xy/.local/lib/python3.6/site-packages/bbconf/bbconf.py", line 170, in insert_bedsets_data
    self._insert_data(index=BEDSET_INDEX, data=data, doc_id=doc_id, **kwargs)
  File "/home/jev4xy/.local/lib/python3.6/site-packages/bbconf/bbconf.py", line 133, in _insert_data
    self[ES_CLIENT_KEY].create(index=index, body=data, id=doc_id, **kwargs)**
  File "/home/jev4xy/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(args, params=params, kwargs)
  File "/home/jev4xy/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 312, in create
    "PUT", _make_path(index, doc_type, id, "_create"), params=params, body=body
  File "/home/jev4xy/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/home/jev4xy/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/jev4xy/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [bedset_bed_ids] of type [text] in document with id '61bacdf617eb93d4a89ecc877c048c09'. Preview of field's value: '{AML_db1=78c0e4753d04b238fc07e4ebe5a02984, AML_db4=a6a08126cb6f4b1953ba0ec8675df85a, AML_db18=114aa8c26961bc3853c19e76e13bebb6, AML_db3=fdd94ac0787599d564b07193e4ec41fd, AML_db19=51b42f44d2b6aa5ed158f7570e3f315b, AML_db16=2b2a9635ecf58248faed88ae0801a25a, AML_db27=bfb50de8567b90105b3407069578e252, AML_db17=000c28e390d63ef52061e373520eba03, AML_db14=459c4eb2616949ee7f90dd3d47198c69, AML_db15=696d961981cbdfb4401516c88d31df70, AML_db9=02fd518818560c28ed20ed98f4c291bd, AML_db6=50e19bd44174bb286aa28ae2a15e7b8f, AML_db5=a78493a2b314afe9f6635c4883f0d44b, AML_db8=a5af5857bfbc3bfc8fea09cb90e67a16, AML_db7=9cd65cf4f07b83af35770c4a098fd4c6, AML_db23=5c7d758dab4ab01528844cc49a2d3a0a, AML_db13=ff5b59612ccf05e8bc7951570db1c3ec, AML_db24=182b34cf67d3462af369c0607c9cabd6, AML_db10=33d4328fe4ff3a472edff81bf8f5d566, AML_db21=cb3c8b8360c2429e4fcb21bdc9d73fcb, AML_db11=2ffb2cedd14f5f1fae7cb765a66d82a3, AML_db22=ae434f64ed499d61872af8b3a943a870, AML_db30=12792bced4c8efd033cf8d2b2afc3fe9, AML_db20=8e7dcf476de36c77bfd253b29f16e751}'")

**Comment by stolarczyk** [comment]
Is this still an issue?

**Comment by joseverdezoto** [comment]
Sorry I forgot to close this. It’s fixed now.
